[package]
name = "rusty_rita"
version = "1.0.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
toml = "0.5.3"
qedchat = { git = "https://git.amesgen.de/amesgen/qedchat-rs.git", rev = "64bb4938" }
crossbeam = "0.7.2"
anyhow = "1.0.1"
log = "0.4.8"
env_logger = "0.7.0"
structopt = "0.3.2"
chrono = "0.4.9"
