[package]
name = "rusty_rita"
version = "1.0.0"
edition = "2018"

[dependencies]
serde = {version = "1.0.99", features = ["derive"]}
toml = "0.5.3"
qedchat = {git = "https://git.amesgen.de/amesgen/qedchat-rs.git"}
crossbeam = "0.7.2"
