[bots]
channel = ["fbot"]

[bots.enabled]
rita = 1

[account]
user = "FranzKönig"
pass = ""


[server]
account = "https://chat.qed-verein.de/rubychat/account', data=credentials)"
websocket = "ss://chat.qed-verein.de/websocket?channel=' + args['channel'] + '&position=-0&version=2'"