foo = "abbbbccc"
[bots]
channel = ["fbot", "test"]


	[bots.enabled]
	rita = 1

[server]
account = "https://chat.qed-verein.de/rubychat/account', data=credentials)"
websocket = "ss://chat.qed-verein.de/websocket?channel=' + args['channel'] + '&position=-0&version=2'"