name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build-artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo fmt -- --check
      - run: |
          cargo build --release
          mkdir artifacts
          cp target/release/rusty_rita artifacts
          cp meta/fbot.service artifacts
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./artifacts
          force_orphan: true
